add test showcase
GE-PPE/NaiveDB pull request #5
Opened 2018-09-27 23:05 UTC by victordamatta

2018-09-30 19:55 UTC, pedro823 requested changes
da uma olhada aí

2018-09-30 19:55 UTC, pedro823 commented on naivedb/test/main_test.go
> +		fmt.Fprintf(conn, fmt.Sprintf("set %s %s", pair.Key, pair.Value))
`fmt.Fprintf(fmt.Sprintf(abc))?`
Por que não só usar `fmt.Fprintf(abc)`?

2018-09-30 19:55 UTC, pedro823 commented on naivedb/test/main_test.go
> +		message = strings.TrimSpace(message)
se der um erro antes disso, pode falhar? Tipo, se `message = nil` e `err = error{}`
Eu inverteria as duas coisas:

```go
message, err := reader.ReadString('\n')
if err != nil {
	t.FailNow()
}
message = strings.TrimSpace(message)
```

2018-10-03 16:25 UTC, victordamatta commented
@pedro823 changes made

2018-10-03 16:35 UTC, pedro823 approved these changes

2018-10-03 16:59 UTC, merged